### ISSUE TITLE
Add mastodon icon

### ISSUE THREAD

**Issue by mguthaus** [bjacquemet/personal-web#37]
Add an option for mastodon to the contact icons.

**Comment by jatkinson1000** [comment]
I have done this here: [jackatkinson.net](https://jackatkinson.net/)

You can see my fork here: https://github.com/jatkinson1000/personal-web with the relevant svg addition for mastodon here: https://github.com/jatkinson1000/personal-web/blob/05d0056a02f3571480b02f5205d441601a04b43c/layouts/partials/svg.html#L272

And add something like the following to `config.toml`:
```toml
[[menu.social]]
  name = "mastodon"
  url = "https://fosstodon.org/@jatkinson1000"
  weight = -10
```
